### ISSUE TITLE
[Bug] App crashes on incorrect answer to true/false question

### ISSUE THREAD

**Issue by Atrate** [tryton-vanmeer/LibreTrivia#24]
Might be related to #23 

Log:
```
11-11 14:44:36.292 E/AndroidRuntime(12047): FATAL EXCEPTION: main
11-11 14:44:36.292 E/AndroidRuntime(12047): Process: io.github.trytonvanmeer.libretrivia, PID: 12047
11-11 14:44:36.292 E/AndroidRuntime(12047): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setBackgroundTintList(android.content.res.ColorStateList)' on a null object reference
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at io.github.trytonvanmeer.libretrivia.activities.TriviaGameActivity.onAnswerClick(TriviaGameActivity.java:177)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at io.github.trytonvanmeer.libretrivia.fragments.TriviaQuestionFragment$AnswerButtonListener.onClick(TriviaQuestionFragment.java:114)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at android.view.View.performClick(View.java:6619)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at android.view.View.performClickInternal(View.java:6596)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at android.view.View.access$3100(View.java:780)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at android.view.View$PerformClick.run(View.java:25951)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at android.os.Handler.handleCallback(Handler.java:873)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at android.os.Looper.loop(Looper.java:193)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at android.app.ActivityThread.main(ActivityThread.java:6698)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at java.lang.reflect.Method.invoke(Native Method)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
11-11 14:44:36.292 E/AndroidRuntime(12047): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)

```

**Comment by awesome14** [comment]
I can verify this bug. Cleared cache and data, forced stop, relaunched, and it seems to work well now. But went back to same problem after a few minutes of use.

**Comment by WPFilmmaker** [comment]
Can confirm here too on Android 7.0 (moto g4).

**Comment by Toiletmason** [comment]
I also have this bug. Android 8.1.0

**Comment by lillelilje** [comment]
Can confirm this bug. Very bothersome.
